language: php

php:
  - 7.0
  - 7.1

before_script:
  - composer update -n
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit
  # - ./vendor/bin/phpunit --coverage-text --coverage-clover ./clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 --extensions=php ./src ./tests

after_script:
  - ./vendor/bin/coveralls -v

before_install:
  - pip install --user codecov

after_success:
  - codecov
